server:
  #debug开发模式 release生产模式
  mode : 'debug'
  port : ':8088'

db:
  type : 'mysql'
  username : 'zyhkDev'
  password : 'zyhkDev'
  host : '192.168.217.201'
  port : '3306'
  name : 'zyhk'

# db:
#   type : 'mysql'
#   username : 'zyhk'
#   password : 'zyhk'
#   host : '192.168.203.201'
#   port : '3306'
#   name : 'zyhk'